// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtv3BoQJiUw7lYxFlo7bpGzz5rXfmV-8k',
    appId: '1:24907212436:web:06252b433f045c238d3681',
    messagingSenderId: '24907212436',
    projectId: 'travel-poject',
    authDomain: 'travel-poject.firebaseapp.com',
    storageBucket: 'travel-poject.firebasestorage.app',
    measurementId: 'G-W1TT8JXCN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu3ZJ-bKRBPLTcqsfIlEE7fJVbKx6YYvo',
    appId: '1:24907212436:android:77d59b70bb9bd8e88d3681',
    messagingSenderId: '24907212436',
    projectId: 'travel-poject',
    storageBucket: 'travel-poject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABLROuaunYVuS2OA5gHMeMXYTY3-v_9eg',
    appId: '1:24907212436:ios:fe1a44f0789670a48d3681',
    messagingSenderId: '24907212436',
    projectId: 'travel-poject',
    storageBucket: 'travel-poject.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABLROuaunYVuS2OA5gHMeMXYTY3-v_9eg',
    appId: '1:24907212436:ios:fe1a44f0789670a48d3681',
    messagingSenderId: '24907212436',
    projectId: 'travel-poject',
    storageBucket: 'travel-poject.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtv3BoQJiUw7lYxFlo7bpGzz5rXfmV-8k',
    appId: '1:24907212436:web:06252b433f045c238d3681',
    messagingSenderId: '24907212436',
    projectId: 'travel-poject',
    authDomain: 'travel-poject.firebaseapp.com',
    storageBucket: 'travel-poject.firebasestorage.app',
    measurementId: 'G-W1TT8JXCN9',
  );
}
